import AppLog
import Foundation

/// Translates the chrome's `TerminalTheme` into ghostty config-file text — the seam's
/// theme vocabulary driving the libghostty backend, so the chrome stays the source of
/// truth for appearance on both backends. libghostty accepts configuration only from
/// files (no setter API), so `GhosttyApp` writes this text to a scratch file and loads
/// it; nothing here reads or touches any user-level ghostty config.
enum GhosttyConfigWriter {
    /// When ghostty runs the cursor shader's draw timer. ghostty's `.true` animates only while
    /// the surface is focused, so a blur freezes the tail mid-decay into a permanent tracer;
    /// `.always` animates regardless of focus. `GhosttySurface` bursts a blurred surface into
    /// `.always` just long enough for the tail to decay, then drops back (ZEN-237).
    enum ShaderAnimation: String {
        case whileFocused = "true"
        case always
    }

    /// The full generated config: theme-derived colors and font, plus the terminal
    /// behavior (cursor shape/thickness, Option semantics) the chrome dials from user config.
    /// A nil `behavior` uses the shipped `TerminalBehavior.default`.
    static func configText(
        for theme: TerminalTheme?, behavior: TerminalBehavior? = nil,
        shaderAnimation: ShaderAnimation = .whileFocused
    ) -> String {
        let behavior = behavior ?? .default
        var lines = [
            "# Generated by zen-term from the chrome's TerminalTheme — do not edit.",
            "cursor-style = \(behavior.ghosttyCursorStyle)",
            "cursor-style-blink = \(behavior.cursorBlink)",
            // Shell integration's cursor-shape-per-mode would override the block with a
            // bar at the prompt; keep the rest (cwd, prompt marking → isBusy) and let
            // cursor-style rule.
            "shell-integration-features = no-cursor",
            "mouse-hide-while-typing = true",
            "font-thicken = true",
            // Option acts as Alt/Meta — ⌥f/⌥b word-nav in readline, Meta chords in
            // vim/emacs — the terminal convention, chosen over macOS accent composing.
            "macos-option-as-alt = \(behavior.optionAsAlt)",
        ]
        // Widen the bar/underline cursor (ghostty's base is a nearly invisible 1px). A delta
        // from that base; the block cursor fills the cell and ignores it.
        if let delta = behavior.ghosttyCursorThicknessDelta {
            lines.append("adjust-cursor-thickness = \(delta)")
        }
        if let theme {
            lines.append("font-family = \(theme.fontName)")
            lines.append("font-size = \(theme.fontSize)")
            lines.append("background = \(theme.background.hex)")
            lines.append("foreground = \(theme.foreground.hex)")
            lines.append("cursor-color = \(theme.cursor.hex)")
            lines.append("selection-background = \(theme.selectionBackground.hex)")
            for (index, color) in theme.ansi.enumerated() {
                lines.append("palette = \(index)=\(color.hex)")
            }
        }
        // The cursor shader runs as a post-process pass via ghostty's `custom-shader` (that stays
        // ghostty's own key even though the chrome exposes a single `cursor-shader`). The path is
        // already absolute (the chrome resolves the bundled name), so ghostty's file-relative
        // resolution — which would look next to this temp config — never applies. Pin
        // `custom-shader-animation` so it animates regardless of ghostty's default drift; only
        // emit it when there's a shader to animate.
        if let shader = behavior.cursorShader {
            lines.append("custom-shader = \(shader)")
            lines.append("custom-shader-animation = \(shaderAnimation.rawValue)")
        }
        // The chrome's `background-alpha` maps to ghostty's own `background-opacity`, the same
        // rename `cursor-shader` → `custom-shader` above uses. Only emitted below 1, so the
        // default config text stays exactly what it has always been.
        if let opacity = behavior.ghosttyBackgroundOpacity {
            lines.append("background-opacity = \(opacity)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Write the generated config where libghostty can load it and return the path,
    /// or nil if the write failed (the caller falls back to ghostty's own defaults).
    /// The file lives for the process's lifetime — the OS reaps the temp directory.
    ///
    /// `variant` names a separate scratch file. Per-surface configs (ZEN-237) pass one so they
    /// never overwrite the app-global config's file, which every surface loads from. Writes
    /// within a variant are safe to share a path: this all runs on the main thread and
    /// libghostty loads the file inside the same call that wrote it.
    static func writeConfig(
        for theme: TerminalTheme?, behavior: TerminalBehavior? = nil,
        shaderAnimation: ShaderAnimation = .whileFocused, variant: String? = nil
    ) -> String? {
        let suffix = variant.map { "-\($0)" } ?? ""
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent(
                "zenterm-ghostty-config-\(ProcessInfo.processInfo.processIdentifier)\(suffix)")
        do {
            try configText(for: theme, behavior: behavior, shaderAnimation: shaderAnimation)
                .write(to: url, atomically: true, encoding: .utf8)
            return url.path
        } catch {
            Log.error(
                "GhosttyConfigWriter: failed to write generated config: \(error)", category: .config)
            return nil
        }
    }
}

extension TerminalColor {
    /// `#rrggbb` — the color syntax ghostty's config parser accepts.
    var hex: String {
        String(format: "#%02x%02x%02x", red, green, blue)
    }
}
