import AppLog
import Foundation

// libghostty only accepts config from files.
enum GhosttyConfigWriter {
    // `.whileFocused` freezes a blurred cursor tail mid-decay into a tracer; `.always` does not.
    enum ShaderAnimation: String {
        case whileFocused = "true"
        case always
    }

    static let gridInset: CGFloat = 2

    // `fontSize` must carry a surface's stepped size: `updateConfig` resets unadjusted sizes to the config's.
    static func configText(
        for theme: TerminalTheme?, behavior: TerminalBehavior? = nil,
        shaderAnimation: ShaderAnimation = .whileFocused,
        fontSize: CGFloat? = nil
    ) -> String {
        let behavior = behavior ?? .default
        var lines = [
            "# Generated by zen-term from the chrome's TerminalTheme — do not edit.",
            "theme = light:\(lightSchemeThemePath),dark:\(darkSchemeThemePath)",
            "cursor-style = \(behavior.ghosttyCursorStyle)",
            "cursor-style-blink = \(behavior.cursorBlink)",
            "shell-integration-features = no-cursor",
            "mouse-hide-while-typing = true",
            "window-padding-x = \(Int(gridInset))",
            "window-padding-y = \(Int(gridInset))",
            "macos-option-as-alt = \(behavior.optionAsAlt)",
        ]
        if let delta = behavior.ghosttyCursorThicknessDelta {
            lines.append("adjust-cursor-thickness = \(delta)")
        }
        if behavior.fontThicken {
            lines.append("font-thicken = true")
        }
        if let theme {
            lines.append("font-family = \(theme.fontName)")
            lines.append("font-size = \(fontSize ?? theme.fontSize)")
            lines.append("background = \(theme.background.hex)")
            lines.append("foreground = \(theme.foreground.hex)")
            lines.append("cursor-color = \(theme.cursor.hex)")
            lines.append("selection-background = \(theme.selectionBackground.hex)")
            if let color = theme.selectionForeground {
                lines.append("selection-foreground = \(color.hex)")
            }
            if let color = theme.searchForeground { lines.append("search-foreground = \(color.hex)") }
            if let color = theme.searchBackground { lines.append("search-background = \(color.hex)") }
            if let color = theme.searchSelectedForeground {
                lines.append("search-selected-foreground = \(color.hex)")
            }
            if let color = theme.searchSelectedBackground {
                lines.append("search-selected-background = \(color.hex)")
            }
            for (index, color) in theme.ansi.enumerated() {
                lines.append("palette = \(index)=\(color.hex)")
            }
        }
        if let shader = behavior.cursorShader {
            lines.append("custom-shader = \(shader)")
            lines.append("custom-shader-animation = \(shaderAnimation.rawValue)")
        }
        if let opacity = behavior.ghosttyBackgroundOpacity {
            lines.append("background-opacity = \(opacity)")
        }
        lines += GhosttyUnboundChords.triggers.map { "keybind = \($0)=unbind" }
        return lines.joined(separator: "\n") + "\n"
    }

    // libghostty reports a color scheme only when `theme` is a light/dark pair of distinct paths.
    private static var lightSchemeThemePath: String { schemeThemePath("light") }
    private static var darkSchemeThemePath: String { schemeThemePath("dark") }

    private static func schemeThemePath(_ variant: String) -> String {
        FileManager.default.temporaryDirectory
            .appendingPathComponent(
                "zenterm-ghostty-scheme-\(ProcessInfo.processInfo.processIdentifier)-\(variant)"
            ).path
    }

    // Not `fileExists`: names are pid-scoped and a stale file from a reused pid would load as a theme.
    private static var didWriteSchemeThemeFiles = false

    private static func writeSchemeThemeFiles() {
        guard !didWriteSchemeThemeFiles else { return }
        didWriteSchemeThemeFiles = true
        let contents = """
            # Written by zen-term. Sets nothing, on purpose.
            # Its twin file and this one exist so libghostty treats the theme as conditional,
            # which is what lets a pane report the right color scheme to programs that ask.
            # Every color comes from the generated config next to this file.

            """
        for path in [lightSchemeThemePath, darkSchemeThemePath] {
            do {
                try contents.write(toFile: path, atomically: true, encoding: .utf8)
            } catch {
                Log.error(
                    "GhosttyConfigWriter: failed to write scheme theme file: \(error)",
                    category: .config)
            }
        }
    }

    static func writeConfig(
        for theme: TerminalTheme?, behavior: TerminalBehavior? = nil,
        shaderAnimation: ShaderAnimation = .whileFocused, variant: String? = nil,
        fontSize: CGFloat? = nil
    ) -> String? {
        writeSchemeThemeFiles()
        let suffix = variant.map { "-\($0)" } ?? ""
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent(
                "zenterm-ghostty-config-\(ProcessInfo.processInfo.processIdentifier)\(suffix)")
        do {
            try configText(
                for: theme, behavior: behavior, shaderAnimation: shaderAnimation, fontSize: fontSize
            )
            .write(to: url, atomically: true, encoding: .utf8)
            return url.path
        } catch {
            Log.error(
                "GhosttyConfigWriter: failed to write generated config: \(error)", category: .config)
            return nil
        }
    }
}
